In [6]:
from pycocotools.coco import COCO
import json
import pprint

In [17]:
#!python cocosplit.py --having-annotations --multi-class -s 0.8 train.json train_f0.json valid_f0.json

Saved 18515 entries in train_f0.json and 4629 in valid_f0.json


In [18]:
#!python cocosplit.py --having-annotations --multi-class -s 0.8 train.json train_f1.json valid_f1.json

Saved 18515 entries in train_f1.json and 4629 in valid_f1.json


In [19]:
#!python cocosplit.py --having-annotations --multi-class -s 0.8 train.json train_f2.json valid_f2.json

Saved 18515 entries in train_f2.json and 4629 in valid_f2.json


In [20]:
#!python cocosplit.py --having-annotations --multi-class -s 0.8 train.json train_f3.json valid_f3.json

Saved 18515 entries in train_f3.json and 4629 in valid_f3.json


In [21]:
#!python cocosplit.py --having-annotations --multi-class -s 0.8 train.json train_f4.json valid_f4.json

Saved 18515 entries in train_f4.json and 4629 in valid_f4.json


In [7]:
FULL_JSON = "/opt/ml/object_detection_remote/folded_anns/train.json"
TRAIN_JSON = "/opt/ml/object_detection_remote/folded_anns/train_0.json"
VALID_JSON = "/opt/ml/object_detection_remote/folded_anns/val_0.json"

with open(FULL_JSON, 'r') as outfile:
    full_anno = (json.load(outfile))

with open(TRAIN_JSON, 'r') as outfile:
    train_anno = (json.load(outfile))

with open(VALID_JSON, 'r') as outfile:
    valid_anno = (json.load(outfile))

In [10]:
sorted(full_anno.keys())

['annotations', 'categories', 'images', 'info', 'licenses']

In [11]:
sorted(train_anno.keys())

['annotations', 'categories', 'images', 'info', 'licenses']

In [12]:
print("num_of_img:", len(full_anno["images"]))
print("num_of_anno:", len(full_anno["annotations"]))

num_of_img: 4883
num_of_anno: 23144


In [13]:
print("num_of_img:", len(train_anno["images"]))
print("num_of_anno:", len(train_anno["annotations"]))

num_of_img: 3914
num_of_anno: 18633


In [14]:
print("num_of_img:", len(valid_anno["images"]))
print("num_of_anno:", len(valid_anno["annotations"]))

num_of_img: 969
num_of_anno: 4511


In [86]:
import json
import numpy as np
from sklearn.model_selection import StratifiedGroupKFold

# load json
annotation = "/opt/level2_objectdetection_cv-level2-cv-04/folded_anns/train.json" # 개인 train.json 파일 위치 입력하세요

with open(annotation) as f:
    data = json.load(f)
    
var = [(ann['image_id'], ann['category_id']) for ann in data['annotations']] ## 이미지 id와 카테고리 id만 가져옴

X = np.ones((len(data['annotations']),1)) # annotations의 길이만큼 1을 생성함
y = np.array([v[1] for v in var]) # 카테고리의 id가 담긴 np를 생성함.
groups = np.array([v[0] for v in var]) # img_id가 담긴 np를 생성함.

cv = StratifiedGroupKFold(n_splits=5, shuffle=True, random_state=411)

train_indices = list()
val_indices = list()
for train_idx, val_idx in cv.split(X, y, groups):
    train_indices.append(train_idx)
    val_indices.append(val_idx)

print(len(groups[train_idx]))
print(len(y[train_idx]))

18783
18783


In [102]:
num_of_img = set([i[0] for i in var])
print('num of obj:',len(data['annotations']))
print('num of img:', len(num_of_img))

num of obj: 23144
num of img: 4883


In [103]:
print(data.keys())

dict_keys(['info', 'licenses', 'images', 'categories', 'annotations'])


In [104]:
data['annotations']

[{'image_id': 0,
  'category_id': 0,
  'area': 257301.66,
  'bbox': [197.6, 193.7, 547.8, 469.7],
  'iscrowd': 0,
  'id': 0},
 {'image_id': 1,
  'category_id': 3,
  'area': 10402.56,
  'bbox': [0.0, 407.4, 57.6, 180.6],
  'iscrowd': 0,
  'id': 1},
 {'image_id': 1,
  'category_id': 7,
  'area': 26259.36,
  'bbox': [0.0, 455.6, 144.6, 181.6],
  'iscrowd': 0,
  'id': 2},
 {'image_id': 1,
  'category_id': 4,
  'area': 69096.17,
  'bbox': [722.3, 313.4, 274.3, 251.9],
  'iscrowd': 0,
  'id': 3},
 {'image_id': 1,
  'category_id': 5,
  'area': 24164.58,
  'bbox': [353.2, 671.0, 233.7, 103.4],
  'iscrowd': 0,
  'id': 4},
 {'image_id': 1,
  'category_id': 5,
  'area': 188324.4,
  'bbox': [3.7, 448.5, 778.2, 242.0],
  'iscrowd': 0,
  'id': 5},
 {'image_id': 1,
  'category_id': 0,
  'area': 38908.72,
  'bbox': [425.3, 681.9, 216.4, 179.8],
  'iscrowd': 0,
  'id': 6},
 {'image_id': 1,
  'category_id': 7,
  'area': 7391.52,
  'bbox': [92.4, 601.7, 139.2, 53.1],
  'iscrowd': 0,
  'id': 7},
 {'image_

In [106]:
# 뽑힌 annots를 다 가지고 옴
train_annots = []
val_annots = []
for train_idx, valid_idx in zip(train_indices, val_indices):
    train_annot = np.array(data['annotations'])[train_idx].tolist()
    val_annot = np.array(data['annotations'])[valid_idx].tolist()
    train_annots.append(train_annot)
    val_annots.append(val_annot)

In [128]:
train_img_indices = []
for train_annot in train_annots:
    ids = list()
    for d in train_annot:
        ids.append(d['image_id'])
    train_img_indices.append(list(set(ids)))

val_img_indices = []
for val_annot in val_annots:
    ids = list()
    for d in val_annot:
        ids.append(d['image_id'])
    val_img_indices.append(list(set(ids)))

In [129]:
train_imgs = []
for img_indice in train_img_indices:
    train_img = np.array(data['images'])[img_indice].tolist()
    train_imgs.append(train_img)

val_imgs = []
for img_indice in val_img_indices:
    val_img = np.array(data['images'])[img_indice].tolist()
    val_imgs.append(val_img)

In [136]:
data.keys()

dict_keys(['info', 'licenses', 'images', 'categories', 'annotations'])

In [139]:
# for ord, (imgs, annots) in enumerate(zip(train_imgs, train_annots)):
#     temp_json = dict()
#     temp_json['info'] = data['info']
#     temp_json['licenses'] =  data['licenses']
#     temp_json['images'] = imgs
#     temp_json['categories'] = data['categories']
#     temp_json['annotations'] = annots
#     with open(f'train_{ord}.json', 'w') as outfile:
#         json.dump(temp_json, outfile, indent=2)

In [140]:
# for ord, (imgs, annots) in enumerate(zip(val_imgs, val_annots)):
#     temp_json = dict()
#     temp_json['info'] = data['info']
#     temp_json['licenses'] =  data['licenses']
#     temp_json['images'] = imgs
#     temp_json['categories'] = data['categories']
#     temp_json['annotations'] = annots
#     with open(f'val_{ord}.json', 'w') as outfile:
#         json.dump(temp_json, outfile, indent=2)

In [146]:
annotation = "/opt/level2_objectdetection_cv-level2-cv-04/folded_anns/train_0.json"

with open(annotation) as f:
    data = json.load(f)
    
var0 = [(ann['image_id'], ann['category_id']) for ann in data['annotations']] ## 이미지 id와 카테고리 id만 가져옴


annotation = "/opt/level2_objectdetection_cv-level2-cv-04/folded_anns/train_1.json"

with open(annotation) as f:
    data = json.load(f)
    
var1 = [(ann['image_id'], ann['category_id']) for ann in data['annotations']] ## 이미지 id와 카테고리 id만 가져옴

In [147]:
y0 = np.array([v[1] for v in var0]) # 카테고리의 id가 담긴 np를 생성함.
groups0 = np.array([v[0] for v in var0]) # img_id가 담긴 np를 생성함.

y1 = np.array([v[1] for v in var1]) # 카테고리의 id가 담긴 np를 생성함.
groups1 = np.array([v[0] for v in var1]) # img_id가 담긴 np를 생성함.

set(y0)
set(groups0) ==  set(groups1) # duplicated check

False

In [78]:
data.keys()

dict_keys(['info', 'licenses', 'images', 'categories', 'annotations'])

In [85]:
np.array(data['images'])

[{'width': 1024,
  'height': 1024,
  'file_name': 'train/0000.jpg',
  'license': 0,
  'flickr_url': None,
  'coco_url': None,
  'date_captured': '2020-12-26 14:44:23',
  'id': 0},
 {'width': 1024,
  'height': 1024,
  'file_name': 'train/0001.jpg',
  'license': 0,
  'flickr_url': None,
  'coco_url': None,
  'date_captured': '2021-01-10 16:30:39',
  'id': 1},
 {'width': 1024,
  'height': 1024,
  'file_name': 'train/0002.jpg',
  'license': 0,
  'flickr_url': None,
  'coco_url': None,
  'date_captured': '2020-12-27 17:55:52',
  'id': 2},
 {'width': 1024,
  'height': 1024,
  'file_name': 'train/0003.jpg',
  'license': 0,
  'flickr_url': None,
  'coco_url': None,
  'date_captured': '2021-03-31 12:10:36',
  'id': 3},
 {'width': 1024,
  'height': 1024,
  'file_name': 'train/0004.jpg',
  'license': 0,
  'flickr_url': None,
  'coco_url': None,
  'date_captured': '2021-01-01 18:52:38',
  'id': 4},
 {'width': 1024,
  'height': 1024,
  'file_name': 'train/0005.jpg',
  'license': 0,
  'flickr_url': 

In [63]:
full_img_id = [i[0] for i in var]

In [73]:
np.array(data['images'])[list(set(full_img_id))]

array([{'width': 1024, 'height': 1024, 'file_name': 'train/0000.jpg', 'license': 0, 'flickr_url': None, 'coco_url': None, 'date_captured': '2020-12-26 14:44:23', 'id': 0},
       {'width': 1024, 'height': 1024, 'file_name': 'train/0001.jpg', 'license': 0, 'flickr_url': None, 'coco_url': None, 'date_captured': '2021-01-10 16:30:39', 'id': 1},
       {'width': 1024, 'height': 1024, 'file_name': 'train/0002.jpg', 'license': 0, 'flickr_url': None, 'coco_url': None, 'date_captured': '2020-12-27 17:55:52', 'id': 2},
       ...,
       {'width': 1024, 'height': 1024, 'file_name': 'train/4880.jpg', 'license': 0, 'flickr_url': None, 'coco_url': None, 'date_captured': '2020-12-24 11:25:46', 'id': 4880},
       {'width': 1024, 'height': 1024, 'file_name': 'train/4881.jpg', 'license': 0, 'flickr_url': None, 'coco_url': None, 'date_captured': '2021-01-05 11:01:18', 'id': 4881},
       {'width': 1024, 'height': 1024, 'file_name': 'train/4882.jpg', 'license': 0, 'flickr_url': None, 'coco_url': None, 

In [60]:
groups[train_idx] # 이 인덱스들이 image_id들임
print(len(set(groups[train_idx])))
print(len(set(groups[val_idx])))


3909
974


In [30]:
print(groups[train_idx])
print(y[train_idx])

[   0    1    1 ... 4882 4882 4882]
[0 3 7 ... 0 1 1]


In [42]:
train_idx

array([    0,     1,     2, ..., 23141, 23142, 23143])

In [45]:
print(data.keys())
data

# category_id, 클래스의 종류


dict_keys(['info', 'licenses', 'images', 'categories', 'annotations'])


{'info': {'year': 2021,
  'version': '1.0',
  'description': 'Recycle Trash',
  'contributor': 'Upstage',
  'url': None,
  'date_created': '2021-02-02 01:10:00'},
 'licenses': [{'id': 0,
   'name': 'CC BY 4.0',
   'url': 'https://creativecommons.org/licenses/by/4.0/deed.ast'}],
 'images': [{'width': 1024,
   'height': 1024,
   'file_name': 'train/0000.jpg',
   'license': 0,
   'flickr_url': None,
   'coco_url': None,
   'date_captured': '2020-12-26 14:44:23',
   'id': 0},
  {'width': 1024,
   'height': 1024,
   'file_name': 'train/0001.jpg',
   'license': 0,
   'flickr_url': None,
   'coco_url': None,
   'date_captured': '2021-01-10 16:30:39',
   'id': 1},
  {'width': 1024,
   'height': 1024,
   'file_name': 'train/0002.jpg',
   'license': 0,
   'flickr_url': None,
   'coco_url': None,
   'date_captured': '2020-12-27 17:55:52',
   'id': 2},
  {'width': 1024,
   'height': 1024,
   'file_name': 'train/0003.jpg',
   'license': 0,
   'flickr_url': None,
   'coco_url': None,
   'date_captur

In [33]:
data['images']

[{'width': 1024,
  'height': 1024,
  'file_name': 'train/0000.jpg',
  'license': 0,
  'flickr_url': None,
  'coco_url': None,
  'date_captured': '2020-12-26 14:44:23',
  'id': 0},
 {'width': 1024,
  'height': 1024,
  'file_name': 'train/0001.jpg',
  'license': 0,
  'flickr_url': None,
  'coco_url': None,
  'date_captured': '2021-01-10 16:30:39',
  'id': 1},
 {'width': 1024,
  'height': 1024,
  'file_name': 'train/0002.jpg',
  'license': 0,
  'flickr_url': None,
  'coco_url': None,
  'date_captured': '2020-12-27 17:55:52',
  'id': 2},
 {'width': 1024,
  'height': 1024,
  'file_name': 'train/0003.jpg',
  'license': 0,
  'flickr_url': None,
  'coco_url': None,
  'date_captured': '2021-03-31 12:10:36',
  'id': 3},
 {'width': 1024,
  'height': 1024,
  'file_name': 'train/0004.jpg',
  'license': 0,
  'flickr_url': None,
  'coco_url': None,
  'date_captured': '2021-01-01 18:52:38',
  'id': 4},
 {'width': 1024,
  'height': 1024,
  'file_name': 'train/0005.jpg',
  'license': 0,
  'flickr_url': 

In [12]:
var

[(0, 0),
 (1, 3),
 (1, 7),
 (1, 4),
 (1, 5),
 (1, 5),
 (1, 0),
 (1, 7),
 (1, 0),
 (2, 3),
 (3, 2),
 (3, 6),
 (4, 1),
 (4, 1),
 (4, 1),
 (4, 1),
 (4, 1),
 (4, 0),
 (5, 7),
 (5, 0),
 (5, 0),
 (5, 0),
 (5, 5),
 (5, 5),
 (5, 7),
 (5, 7),
 (5, 7),
 (5, 7),
 (5, 7),
 (5, 7),
 (5, 7),
 (5, 1),
 (5, 1),
 (5, 7),
 (5, 1),
 (5, 1),
 (5, 0),
 (5, 1),
 (5, 5),
 (5, 0),
 (6, 1),
 (7, 9),
 (7, 9),
 (8, 6),
 (8, 0),
 (8, 7),
 (8, 7),
 (8, 7),
 (8, 7),
 (8, 7),
 (9, 2),
 (10, 0),
 (11, 0),
 (12, 1),
 (12, 1),
 (12, 1),
 (13, 6),
 (13, 7),
 (13, 7),
 (13, 6),
 (13, 7),
 (13, 1),
 (13, 1),
 (13, 1),
 (13, 7),
 (13, 1),
 (13, 3),
 (13, 5),
 (13, 5),
 (13, 5),
 (13, 5),
 (13, 5),
 (14, 9),
 (14, 9),
 (14, 7),
 (14, 9),
 (14, 3),
 (15, 6),
 (15, 3),
 (15, 6),
 (16, 6),
 (17, 0),
 (18, 6),
 (18, 6),
 (18, 6),
 (18, 6),
 (18, 7),
 (18, 6),
 (18, 7),
 (18, 6),
 (18, 7),
 (18, 7),
 (18, 3),
 (19, 2),
 (19, 7),
 (19, 7),
 (19, 7),
 (19, 7),
 (19, 7),
 (19, 0),
 (19, 3),
 (19, 1),
 (19, 7),
 (20, 7),
 (21, 7),
 